/*
 * Copyright 2014-2023 Web Firm Framework
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.webfirmframework.wffweb.util;

import static org.junit.Assert.*;

import java.security.NoSuchAlgorithmException;

import org.junit.Test;

public class HashUtilTest {
    
    @Test
    public void testHashSHA256() throws NoSuchAlgorithmException {
        assertEquals("Kh8K+0/ZGGUJz40u7V2q+zTMKqFqV9HMsCyef9n9aPs=", HashUtil.hashSHA256("Hello webfirmframework"));
        final String hashSHA256 = HashUtil.hashSHA256("Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                + "Hello webfirmframework"
                );
        System.out.println(hashSHA256.length());
        assertEquals(44, hashSHA256.length());
    }

    @Test
    public void testHashSHA384() throws NoSuchAlgorithmException {
        assertEquals("RZDeMlkNh7DS5dfofurW+copvbLj4QY7W/03wLIo2jI33mqXF2xDNbKXnumstQOS", HashUtil.hashSHA384("Hello webfirmframework"));
    }

    @Test
    public void testHashSHA512() throws NoSuchAlgorithmException {
        assertEquals("ghMAt8A5BbfxVoJuLHe/Kg8InW4UDyJH9pCM6T7xTo6WngUisFwvrn62TWu6IvYJKHhwKhKqFeY8+s9zSXQJ2g==", HashUtil.hashSHA512("Hello webfirmframework"));
    }

    @Test
    public void testHashInBase64() throws NoSuchAlgorithmException {
        assertEquals("Kh8K+0/ZGGUJz40u7V2q+zTMKqFqV9HMsCyef9n9aPs=", HashUtil.hashInBase64("Hello webfirmframework", "SHA-256"));
        assertEquals("RZDeMlkNh7DS5dfofurW+copvbLj4QY7W/03wLIo2jI33mqXF2xDNbKXnumstQOS", HashUtil.hashInBase64("Hello webfirmframework", "SHA-384"));
        assertEquals("ghMAt8A5BbfxVoJuLHe/Kg8InW4UDyJH9pCM6T7xTo6WngUisFwvrn62TWu6IvYJKHhwKhKqFeY8+s9zSXQJ2g==", HashUtil.hashInBase64("Hello webfirmframework", "SHA-512"));
    }

}
